config/routes.rb
Rails.application.routes.draw do
  get 'evenements/index'
  get 'evenements/show'
  get 'home/index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"  # Définir la route racine

  get 'home', to: 'home#index'
  get 'lunch', to: 'lunch#index'
  get 'plats', to: 'plats#index'
  get 'photos', to: 'photos#index'
  get 'evenements', to: 'evenements#index'
  get 'contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evenement.rb
class Evenement < ApplicationRecord
end

app/models/photo.rb
# app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
end

app/models/plat.rb
class Plat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/concerns/lunch_controller.rb
class LunchController < ApplicationController
  def index
  end
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/plats_controller.rb
class PlatsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/plats_helper.rb
module PlatsHelper
end

app/views/contact/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Page</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <!-- Contact Banner -->
  <div class="contact-banner">
    <%= image_tag 'contact.png', alt: 'Tapas Image', class: 'contact-image img-fluid w-100' %>
  </div>
  <!-- Contact Information -->
  <div class="container my-5 contact-container text-center">
      <div class="row justify-content-center">
        <div class="col-12">
          <h1 class="contact-title">Nous contacter</h1>
          <p>Notre spot au parc 2000</p>
          <p>84 Rue Maurice Béjahrt</p>
          <p>34080 Montpellier</p>
          <p class="mt-3"><span class="text-orange">06 12 60 12 45</span></p>
          <p><a href="mailto:le6iemecontinent@gmail.com" class="text-orange">le6iemecontinent@gmail.com</a></p>
        </div>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/evenements/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Evenements</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <div class="event-banner">
    <%= image_tag 'tapas.jpg', alt: 'Tapas Image', class: 'event-image' %>
    <div class="event-text">
      <div class="container my-5 event-container">
        <h1 class="event-title">Nos prochains événements</h1>
        <h2>Saison estivale 2024:</h2>
        <ul>
          <li><strong>26/05</strong> - Chateau d'Ô - Montpellier</li>
          <li><strong>24/06 - 31/08</strong> - Les marchés nocturnes du lundi soir - Pignan</li>
          <li><strong>04/07</strong> - Les jeudis terroirs - Clermont l'Hérault</li>
          <li><strong>18/07</strong> - Soirée estivale Chateau de la Dournie - Saint-Chinian</li>
          <li><strong>18/07</strong> - Les jeudis terroirs - Clermont l'Hérault</li>
          <li><strong>19/07</strong> - Les Nocturnes au Salagou - Lac du Salagou</li>
          <li><strong>01/08</strong> - Soirée estivale Chateau de la Dournie - Saint-Chinian</li>
          <li><strong>01/08</strong> - Les jeudis terroirs - Clermont l'Hérault</li>
          <li><strong>15/08</strong> - Soirée estivale Chateau de la Dournie - Saint-Chinian</li>
        </ul>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/evenements/show.html.erb
<h1>Evenements#show</h1>
<p>Find me in app/views/evenements/show.html.erb</p>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Page</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>

  <div class="home-banner">
    <%= image_tag 'home.png', alt: 'Home Image', class: 'home-image img-fluid w-100' %>
  </div>
  <!-- Contact Information -->
  <div class="container my-5 tataki-container text-center">
     <div class="row justify-content-center">
        <div class="col-12">
          <h1 class="entry-title">Le 6ième Continent vous offre un voyage culinaire</h1>
          <h2>de la Streetfood à la Bistronomie</h2>
          <div class="description">
         <p>Notre cuisine gastro-nomade se demarque par ses influences asiatiques, mediterranien et orientales.</p>
         <p>Une cuisine passionnée par le voyage, une cuisine de partage, basée aux produits de saison & locaux.</p>
         <p> * * * </p>
         <h2>Événementiel</h2>
         <h3>Soirées privées, anniversaires, lendemain de mariage, festivals...</h3>
         <p>Nous vous proposons des saveurs 100% personnalisées.</p>
         <p>Laissez-vous séduire par nos savoureuses créations.</p>
        </div>
     </div>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Le 6ieme Continent</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FontAwesome pour les icônes -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <!-- Bootstrap CSS 5.3.3 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap">

  <!-- Lightbox CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet">

  <!-- Rails CSRF et CSP Meta Tags -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Fichier CSS principal -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Fichier JS principal -->
  <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    /* Style général du corps */
    body {
      background-color: #111; /* Fond sombre */
      font-family: 'Poppins', sans-serif; /* Police élégante */
      color: #eee; /* Couleur du texte claire */
      padding-top: 180px; /* Ajustez la valeur pour laisser suffisamment d'espace pour les bannières */
    }

    /* Style de la bannière blanche en haut */
    .top-banner {
      z-index: 1001;
      height: 45px;
      text-align: right;
      padding: 10px;
    }

    /* Bannière noire collante */
    .banner_sticky {
      background-color: black;
      background-image: linear-gradient(180deg, rgba(0, 0, 0, .96) 0, rgba(0, 0, 0, .4) 100%);
      position: fixed;
      top: 20px;
      left: 0;
      z-index: 1000;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding-top: 20px;
      background-size: cover;
      background-position: center center;
      background-repeat: no-repeat;
      width: 100%;
    }

    /* Contenu général */
    .content {
      padding: 40px 15px;
      text-align: center;
    }

    /* Style des titres */
    h1, h2, h3 {
      color: white;
    }

    /* Style des paragraphes */
    p {
      color: #bbb;
      font-size: 1.2em;
      line-height: 1.6;
      margin-bottom: 20px;
    }

    /* Style du logo */
    .logo-container {
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .logo {
      max-width: 160px;
      height: auto;
    }

    /* Style des icônes sociales */
    .social-icons {
      color: #999;
      font-size: 1.2em;
    }

    /* .social-icons a {
      margin-left: 15px;
      font-size: 1.5em;
      color: #eee;
    } */

    .fa-brands, .fab {
      font-family: "Font Awesome 6 Brands";
      font-weight: 700;
      padding-right: 10px;
    }

    .social-icons a:hover {
      color: #EEEEEE;
    }

    /* Centrage de l'icône du menu */
    .navbar-toggler {
      margin: 0 auto;
      display: flex;
      justify-content: center;
      outline: none;/* Pour éviter tout autre box-shadow qui pourrait être appliqué */
      box-shadow: none;
    }

    .navbar-toggler:focus {
      outline: none;
      box-shadow: none;
    }


  .navbar-toggler-icon:focus {
    outline: none;
    box-shadow: none;
  }


    /* Ajustement des rubriques dans le menu */
    .navbar-collapse {
      text-align: left;
    }

    .navbar-nav {
      display: flex;
      flex-direction: row; /* Menu en ligne */
      align-items: center;
      width: auto; /* Chaque rubrique prend sa propre taille */
    }

    .nav-link.invisible-button {
      font-weight: 200;
      font-family: 'Poppins', sans-serif;
      color: white !important;
      text-decoration: none;
      cursor: pointer;
      font-size: 14px;
      padding: 14px 0px;
    }

    .nav-link.invisible-button:hover {
      color: rgb(88, 88, 104) !important;
      transition-duration: 0.4s;
      transition-timing-function: ease-in-out;
    }

    /* Style pour les petits écrans */
    @media (max-width: 767px) {
      .navbar-nav {
        flex-direction: column !important;
        align-items: center;
        width: 100%;
      }

      .nav-item {
        margin-bottom: 15px;
        width: 100%;
      }

      .nav-link {
        text-align: center;
        flex-direction: column;
        width: 100%;
      }

      .top-banner {
        height: auto;
        padding: 5px 0;
      }

      .social-icons {
        font-size: 14px;
        padding: 8px;
      }

      .banner_sticky {
        padding-top: 35px;
      }

      .logo {
        max-width: 80px;
        height: auto;
      }

      .navbar-toggler {
        margin: 0 auto;
      }

      .navbar-toggler:focus {
        outline: none;
        box-shadow: none;
      }


      .navbar-collapse {
        text-align: center;
      }
    }

    /* Style pour les écrans larges */
    @media (min-width: 768px) {
      .top-banner {
        padding: 10px 0;
      }

      .logo-container {
        margin-bottom: 20px;
      }

      .navbar-nav .nav-item {
        margin-left: 30px;
      }

      .navbar-nav .nav-link {
        color: #eee !important;
        font-size: 1.2em;
      }

      .navbar-nav .nav-link:hover {
        color: #ddd !important;
      }
    }

  </style>
</head>

<body>

  <!-- Bannière blanche -->
  <div class="container-fluid bg-white border-bottom fixed-top top-banner">
    <div class="row">
      <div class="col text-right py-1">
        <a href="https://www.facebook.com/le6iemecontinent" target="_blank" class="social-icons">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://www.instagram.com/le_6ieme_continent?igsh=dHJpNGdhd3B6aXdo" target="_blank" class="social-icons">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
    </div>
  </div>

  <!-- Bannière noire avec logo centré -->
  <div class="banner_sticky">
    <div class="logo-container">
      <a href="<%= root_path %>">
        <%= image_tag 'logo.jpg', alt: 'Logo', class: 'logo' %>
      </a>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-black w-100">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Lunch", lunch_path, class: "nav-link invisible-button" %>
            </li>
            <li class="nav-item">
              <%= link_to "Événements", evenements_path, class: "nav-link invisible-button" %>
            </li>
            <li class="nav-item">
              <%= link_to "Plats Signatures", plats_path, class: "nav-link invisible-button" %>
            </li>
            <li class="nav-item">
              <%= link_to "Photos", photos_path, class: "nav-link invisible-button" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, class: "nav-link invisible-button" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <!-- Contenu principal -->
  <div class="content">
    <%= yield %>
  </div>

  <!-- Bootstrap JS Bundle avec Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

  <!-- Lightbox JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
</body>
</html>

app/views/lunch/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Page</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>

 <div class="lunch-banner">
    <%= image_tag 'lunch.jpeg', alt: 'Lunch Image', class: 'lunch-image img-fluid w-100' %>
  </div>
  <!-- Information -->
  <div class="container my-5 lunch-container text-center">
    <div class="row justify-content-center">
       <div class="col-12">
         <h1 class="lunch-title">Notre spot au parc 2000 à Bureaux and Co</h1>
          <p>Du Lundi à Vendredi</p>
          <p>12 - 14 heures</p>
          <h2 class="orange">à emporter ou sur place</h2>
      </div>
    </div>
  </div>

 <div class="container my-5 plats-lunch-container text-center">
    <div class="plats-lunch-text">
      <div class="row justify-content-center">
          <h1 class="lunch-week-title">Plats de la semaine</h1>
          <ul class="plat-lunch-title">Pita greek style</ul>
           <p class="plat-lunch-description">Poulet effiloché, poivrons grilés, tzatziki, feta, pois chiches frits, menthe, frites & mayo maison 14 €</p>
          <ul class="plat-lunch-title">Burgerlovers</ul>
           <p class="plat-lunch-description">Boeuf Charolais, Cheddar, tomates, salade, sauce au fromage blanc & moutarde à l'ancienne, frites & mayo maison 15€</p>
          <ul class="plat-lunch-title">Döner</ul>
           <p class="plat-lunch-description">Veau et Dinde effiloché épicés, choux rouge, sauce au fromage blanc & citron vert, menthe, frites & mayo maison 15€</p>
          <ul class="plat-lunch-title">Banh Mi du 6ième Continent</ul>
           <p class="plat-lunch-description">Poulet effiloché au curry rouge, citronnelle, thaï basilic, choux chinois, pousses de soja, coriandre, cacahètes 14€</p>
          <ul class="plat-lunch-title">Ceviche du Moment</ul>
           <p class="plat-lunch-description">Poisson du jour, citron vert, tagliatelles de courgettes, mangue, concombres, coriandre, mais frits 14€ </p>
          <ul class="plat-lunch-title">Rouille du Chef</ul>
           <p class="plat-lunch-description">Poulpe & Calamar, vin blanc, sauce tomate, olives vertes, anchois, fenouil, carottes, pommes de terre en persillade 13€</p>
          <ul class="plat-lunch-title">Pasta et basta</ul>
           <p class="plat-lunch-description">Linguine, Noix de Saint Jacques snackés, sauce crémeux au Noilly Prat, basilic, citron, courgettes, parmesan 15€</p>

          <h2 class="orange">* * * </h2>
          <h5 class="orange">* Options végétariens disponibles * Menu Plat & Patisserie & Boisson disponible *</h5>
          <h2 class="orange">Decouvrez plein d'autre plats du 6ième Continent</h2>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/photos/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Page</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!-- Lightbox2 CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet">
</head>
<body>

<div class="container my-4">
  <div class="row">
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('photosthai.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'photosthai.jpg', class: 'img-fluid gallery-img', alt: 'Photo Thai' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('ceviche.jpeg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'ceviche.jpeg', class: 'img-fluid gallery-img', alt: 'Image 2' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('tomates.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'tomates.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('pastapalourdes.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'pastapalourdes.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
     <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('tataki.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'tataki.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('fish.png'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'fish.png', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('saumon.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'saumon.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('tarteabricot.jpeg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'tarteabricot.jpeg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('poulpe.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'poulpe.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
     <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('pita.jpeg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'pita.jpeg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('cake.png'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'cake.png', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
     <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('tapas.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'tapas.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('greek.jpeg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'greek.jpeg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('lunch.jpeg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'lunch.jpeg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
     <div class="col-md-4 col-sm-6 mb-4">
      <%= link_to asset_path('estivales.jpg'), data: { lightbox: 'gallery' } do %>
        <%= image_tag 'estivales.jpg', class: 'img-fluid gallery-img', alt: 'Image 3' %>
      <% end %>
    </div>
  </div>
</div>

<!-- Lightbox2 JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox-plus-jquery.min.js"></script>
</body>
</html>

app/views/plats/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Page</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <div class="platsignature-banner">
    <%= image_tag 'platsignature.jpg', alt: 'Chef Image', class: 'platsignautre-image img-fluid w-100' %>
  </div>
  <!-- Contact Information -->
  <div class="container my-5 platsignature-container text-center">
    <div class="platsignature-text">
      <div class="row justify-content-center">
          <p class="plat-description">Voici une selection parmi nos plats signatures</p>
            <ul class="plat-title">Salade de Poulpe</ul>
            <p class="plat-description">Poulpe cuit à basse temperature, poivrons grillés, tomates sechées, caviar d'aubergines, roquette, parmesan</p>
            <ul class="plat-title">Ceviche de Noix Saint Jacques</ul>
            <p class="plat-description">Lait de coco & citron vert, tagliatelles de courgettes, mangue, concombre, coriandre</p>
            <ul class="plat-title">Gravlax</ul>
            <p class="plat-description">Saumon ou Truite mariné à l'aneth, Gin, salade de lentilles corail, crème au citron, basilic</p>
            <ul class="plat-title">Tataki de Thon</ul>
            <p class="plat-description">Wakamee, Houmous aux herbes d'Asie, pousses de soja, Wasabi</p>
            <ul class="plat-title">Carpaccio de Canard</ul>
            <p class="plat-description">Maki de riz, carottes marinés, cacahuètes, soja, coriandre</p>
            <ul class="plat-title">Tartare de Boeuf à la thai</ul>
            <p class="plat-description"> Citronnelle, gingembre, poivrons grillés, thai basilic, sauce Sriracha</p>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>